
## rabbitmq配置 org.springframework.boot.autoconfigure.amqp.RabbitProperties
spring: 
  rabbitmq: 
    host: 
    port: 
    username: 
    password: 
      

##日志配置
logging:
  level:
    org:
      springframework: info